### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by steelsojka** [tomasbjerre/pull-request-notifier-for-stash#30]
I'm getting this error in our stash logs when a pull request is being made:
```
java.io.FileNotFoundException: http://path/to/jenkins/buildWithParameters?token=someToken&BRANCH=refs/heads/testPR
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625) ~[na:1.7.0_75]
	at se.bjurr.prnfs.listener.UrlInvoker.invoke(UrlInvoker.java:103) ~[plugin.9192568710360528632.pull-request-notifier-for-stash-1.12_1429545068000.jar:na]
	at se.bjurr.prnfs.listener.PrnfsPullRequestEventListener$1.invoke(PrnfsPullRequestEventListener.java:49) [plugin.9192568710360528632.pull-request-notifier-for-stash-1.12_1429545068000.jar:na]
	at se.bjurr.prnfs.listener.PrnfsPullRequestEventListener.handleEvent(PrnfsPullRequestEventListener.java:139) [plugin.9192568710360528632.pull-request-notifier-for-stash-1.12_1429545068000.jar:na]
	at se.bjurr.prnfs.listener.PrnfsPullRequestEventListener.onEvent(PrnfsPullRequestEventListener.java:90) [plugin.9192568710360528632.pull-request-notifier-for-stash-1.12_1429545068000.jar:na]
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:36) [atlassian-event-2.3.4.jar:na]
	at com.atlassian.stash.internal.event.AsyncBatchingInvokersTransformer$AsyncInvokerBatch.invoke(AsyncBatchingInvokersTransformer.java:100) [stash-platform-2.12.1.jar:na]
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:46) [atlassian-event-2.3.4.jar:na]
	at com.atlassian.sal.core.executor.ThreadLocalDelegateRunnable.run(ThreadLocalDelegateRunnable.java:38) [sal-core-2.10.15.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
	... 5 frames trimmed
```

NOTE: I changed the url name and the name of the token in the URL.

**Comment by tomasbjerre** [comment]
If you request:
http://path/to/jenkins/buildWithParameters?token=someToken&BRANCH=refs/heads/testPR
With a REST client ( https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo ) you will probably get 404 which results in this log content.

**Comment by steelsojka** [comment]
You're right! I updated the view name in Jenkins and forgot to update the urls in the plugin :/ My bad. Thanks for the response!

**Comment by gilShin** [comment]
I'm having the same issue (BB version 4.3.0 and pull request notifier version 2.12). When I run the URL using the chrome client it works perfectly.
Looking at the log with Debug level I couldn't see anything special except this error.
Do you have a clue? Should I open a new issue?

Thanks
Gil

**Comment by tomasbjerre** [comment]
Did you try to get the URL from the Bitbucket server machine, perhaps with wget or curl?

**Comment by gilShin** [comment]
Hi,

Figured it out using tcpdump. The reason was "host not found" although when I run the curl using commandline, I did it using the same user bitbucket stash is running with (atlbitbucket). 
Very strange. I have added domain to the URL and it works as well.
Can't think of anything else. I do not want to add the host to the hosts file because if IT will decide to change IP, I'll need to remeber to change as well.
/etc/resolv.conf configured correctly with the search DOMAIN.

Any clue?

Thanks
Gil

**Comment by tomasbjerre** [comment]
Ok if the same problem occurs from shell I would just use the ip in Stash, instead of hostname.

**Comment by gilShin** [comment]
No. From command line it works using DNS without domian. 
curl -X POST http://DNS.DOMAIN:8080/job/name/ - works
Same works from stash

curl -X POST http://DNS:8080/job/name/ - works
Doesn't work from stash

curl -X POST http://IP ADDRESS:8080/job/name/ - works
Same works from stash

Hope that is clear now
Gil
