### ISSUE TITLE
NoClassDefFoundError JsonReader

### ISSUE THREAD

**Issue by magnlun** [tomasbjerre/pull-request-notifier-for-stash#61]
I guess you hate me by now, sorry about that.

I tried the new injection URL. When I tried to get a crumb from Jenkins I got this exception:

2015-09-01 06:43:05,752 ERROR [http-nio-8443-exec-35] malu @PGJE6Zx403x259037x0 2xdsja 192.168.1.108 "POST /rest/prnfs-admin/1.0/manual/ HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: Could not initialize class com.jayway.jsonpath.internal.JsonReader
java.lang.NoClassDefFoundError: Could not initialize class com.jayway.jsonpath.internal.JsonReader
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:461) ~[plugin.6253462562142497142.pull-request-notifier-for-stash-1.23_1441086003000.jar:na]
        at se.bjurr.prnfs.listener.PrnfsRenderer$PrnfsVariable$37.resolve(PrnfsRenderer.java:322) ~[plugin.6253462562142497142.pull-request-notifier-for-stash-1.23_1441086003000.jar:na]
        at se.bjurr.prnfs.listener.PrnfsRenderer$PrnfsVariable.resolve(PrnfsRenderer.java:364) ~[plugin.6253462562142497142.pull-request-notifier-for-stash-1.23_1441086003000.jar:na]
        at se.bjurr.prnfs.listener.PrnfsRenderer.render(PrnfsRenderer.java:415) ~[plugin.6253462562142497142.pull-request-notifier-for-stash-1.23_1441086003000.jar:na]
        at se.bjurr.prnfs.listener.PrnfsPullRequestEventListener.notify(PrnfsPullRequestEventListener.java:159) ~[plugin.6253462562142497142.pull-request-notifier-for-stash-1.23_1441086003000.jar:na]
        at se.bjurr.prnfs.ManualResource.post(ManualResource.java:138) ~[plugin.6253462562142497142.pull-request-notifier-for-stash-1.23_1441086003000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.5_1430735632000.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:83) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:100) [atlassian-trusted-apps-core-3.0.8.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1430737736000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.65_1430737738000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.65_1430737738000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.8.1.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
        ... 205 frames trimmed

**Comment by tomasbjerre** [comment]
Thanks for reporting! I will fix it as soon as I can.

**Comment by tomasbjerre** [comment]
If you have time, it would be interesting to know how older releases behave in your installation.
https://github.com/tomasbjerre/pull-request-notifier-for-stash/releases

**Comment by tomasbjerre** [comment]
You can try 1.24, hopefully it is fixed

**Comment by magnlun** [comment]
After updating I got this instead when I try to press configure:
2015-09-01 19:41:50,370 ERROR [http-nio-8443-exec-7] malu @PGJE6Zx1181x275867x1 1hxjcc3 192.168.101.16 "GET /rest/prnfs-admin/1.0/manual/ HTTP/1.1" c.a.p.r.c.e.j.ThrowableExcept
ionMapper Uncaught exception thrown by REST service: No enum constant se.bjurr.prnfs.admin.AdminFormValues.INEJCTION_TYPE.JSONPATH
java.lang.IllegalArgumentException: No enum constant se.bjurr.prnfs.admin.AdminFormValues.INEJCTION_TYPE.JSONPATH
        at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_20]
        at se.bjurr.prnfs.admin.AdminFormValues$INEJCTION_TYPE.valueOf(AdminFormValues.java:23) ~[plugin.1227853662728532728.pull-request-notifier-for-stash-1.25_1441127011000.j
ar:na]
        at se.bjurr.prnfs.settings.SettingsStorage.getPrnfsNotification(SettingsStorage.java:172) ~[plugin.1227853662728532728.pull-request-notifier-for-stash-1.25_1441127011000
.jar:na]
        at se.bjurr.prnfs.settings.SettingsStorage.getPrnfsSettings(SettingsStorage.java:196) ~[plugin.1227853662728532728.pull-request-notifier-for-stash-1.25_1441127011000.jar
:na]
        at se.bjurr.prnfs.ManualResource$2.perform(ManualResource.java:186) ~[plugin.1227853662728532728.pull-request-notifier-for-stash-1.25_1441127011000.jar:na]
        at se.bjurr.prnfs.ManualResource$2.perform(ManualResource.java:183) ~[plugin.1227853662728532728.pull-request-notifier-for-stash-1.25_1441127011000.jar:na]
        at com.atlassian.stash.internal.user.DefaultEscalatedSecurityContext.call(DefaultEscalatedSecurityContext.java:60) ~[stash-service-impl-3.8.1.jar:na]
        at se.bjurr.prnfs.ManualResource.getSettings(ManualResource.java:182) ~[plugin.1227853662728532728.pull-request-notifier-for-stash-1.25_1441127011000.jar:na]
        at se.bjurr.prnfs.ManualResource.get(ManualResource.java:97) ~[plugin.1227853662728532728.pull-request-notifier-for-stash-1.25_1441127011000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.5_1430735632000.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:83) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:100) [atlassian-trusted-apps-core-3.0.8.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1430737736000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.65_1430737738000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.65_1430737738000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.8.1.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
        ... 205 frames trimmed
2015-09-01 19:42:00,932 ERROR [http-nio-8443-exec-35] @PGJE6Zx1182x275933x1 1hxjcc3 192.168.101.16 "GET /mvc/error500 HTTP/1.1" c.a.s.i.web.ErrorPageController There was an unhandled exception loading [/plugins/servlet/prnfs/admin]
java.lang.IllegalArgumentException: No enum constant se.bjurr.prnfs.admin.AdminFormValues.INEJCTION_TYPE.JSONPATH
        at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_20]
        at se.bjurr.prnfs.admin.AdminFormValues$INEJCTION_TYPE.valueOf(AdminFormValues.java:23) ~[na:na]
        at se.bjurr.prnfs.settings.SettingsStorage.getPrnfsNotification(SettingsStorage.java:172) ~[na:na]
        at se.bjurr.prnfs.settings.SettingsStorage.getPrnfsSettings(SettingsStorage.java:196) ~[na:na]
        at se.bjurr.prnfs.admin.ConfigResource$3.perform(ConfigResource.java:119) ~[na:na]
        at se.bjurr.prnfs.admin.ConfigResource$3.perform(ConfigResource.java:116) ~[na:na]
        at com.atlassian.stash.internal.user.DefaultEscalatedSecurityContext.call(DefaultEscalatedSecurityContext.java:60) ~[stash-service-impl-3.8.1.jar:na]
        at se.bjurr.prnfs.admin.ConfigResource.isAdminAllowed(ConfigResource.java:115) ~[na:na]
        at se.bjurr.prnfs.admin.AdminServlet.doGet(AdminServlet.java:47) ~[na:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) ~[na:na]
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181) ~[sitemesh-2.5-atlassian-10.jar:na]
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85) ~[sitemesh-2.5-atlassian-10.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:83) ~[StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) ~[BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) ~[BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:100) ~[atlassian-trusted-apps-core-3.0.8.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) ~[na:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) ~[na:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) ~[na:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) ~[BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) ~[BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) ~[stash-service-impl-3.8.1.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
        ... 188 frames trimmed

**Comment by tomasbjerre** [comment]
I am releasing 1.26 now, it should work =)

**Comment by magnlun** [comment]
Works fine after the last update :)

**Comment by tomasbjerre** [comment]
Nice :)
